# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a489570e4299c1627eed928a9e5b2633453b1516896762e9d557263cc16109a9254155875e16b7bc6b7f7c5ae00e038ab550628fda2c25fa86d3fdf6490f401d

test:
  secret_key_base: 8379016545cf8294ff9fd4f6b0a5326f7bbd516a001d340af6bb4836cdaa4f5897300214690434f9e374b1402d6749a939f66e694f422740f4369781f6938e6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
